# Generated by Django 4.0.7 on 2023-12-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_remove_metadata_codec_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Metadata',
        ),
    ]
