name: Push-to-EC2

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      - name: Log start time
        run: echo "Starting deployment at $(date)"
        
      - name: Checkout the files
        uses: actions/checkout@v3

      - name: Deploy to filesquery server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          SOURCE: ./
          TARGET: ${{ secrets.TARGET_DIR }}
      
      - name: Run Compose Up
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.HOST_DNS }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.EC2_SSH_KEY }}
            port: 22
            script: |
              sudo apt-get update
              cd ${{ secrets.TARGET_DIR }}
              docker compose -f prod.yml up -d --build
              docker rmi $(docker images -f "dangling=true" -q)
              
              